# Generated by Django 5.1.4 on 2025-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='per_sq_feet_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
