# Generated by Django 5.1.4 on 2025-01-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_property_area_alter_property_bathroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='available_for',
            new_name='availableFor',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='per_sq_feet_price',
            new_name='perSqFeetPrice',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_name',
            new_name='propertyName',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='propertyType',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
